// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujhbvfuyakdtqbnjtxnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqaGJ2ZnV5YWtkdHFibmp0eG54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNDM4MDQsImV4cCI6MjA3MjkxOTgwNH0.o2UXP3Dzl5bm8hFf2lTzjpHm_aroT1Z_rz27vh8rsEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});